version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"